spring.application.name=backend
server.port=8080

# Supabase PostgreSQL Connection (Session Pooler)
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.eejhyixxcsjnvpypispe
spring.datasource.password=!123studynook
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Show SQL in logs
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update